'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("skytribe@hotmail.com")>  _
        Public Property EmailSender() As String
            Get
                Return CType(Me("EmailSender"),String)
            End Get
            Set
                Me("EmailSender") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Skydive Snohomish Gift Certificate Purchase")>  _
        Public Property EmailTitle() As String
            Get
                Return CType(Me("EmailTitle"),String)
            End Get
            Set
                Me("EmailTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LBU2SR9;Initial Catalog=JumpRunTraining;Integrated Security=T"& _ 
            "rue;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationInt"& _ 
            "ent=ReadWrite;MultiSubnetFailover=False")>  _
        Public Property DBConnectionString() As String
            Get
                Return CType(Me("DBConnectionString"),String)
            End Get
            Set
                Me("DBConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\TEMP")>  _
        Public Property PDFOutputFolder() As String
            Get
                Return CType(Me("PDFOutputFolder"),String)
            End Get
            Set
                Me("PDFOutputFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.live.com")>  _
        Public Property SMTPClient() As String
            Get
                Return CType(Me("SMTPClient"),String)
            End Get
            Set
                Me("SMTPClient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property SMTPPort() As String
            Get
                Return CType(Me("SMTPPort"),String)
            End Get
            Set
                Me("SMTPPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("skytribe@hotmail.com")>  _
        Public Property SMTPClientUser() As String
            Get
                Return CType(Me("SMTPClientUser"),String)
            End Get
            Set
                Me("SMTPClientUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Icarus365")>  _
        Public Property SMTPClientPassword() As String
            Get
                Return CType(Me("SMTPClientPassword"),String)
            End Get
            Set
                Me("SMTPClientPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1 Airport Way"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Snohomish"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WA 98999")>  _
        Public Property ReturnAddress() As String
            Get
                Return CType(Me("ReturnAddress"),String)
            End Get
            Set
                Me("ReturnAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("17821 20 ave se"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Mill Creek"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WA 98012")>  _
        Public Property ReturnAddressDiscreet() As String
            Get
                Return CType(Me("ReturnAddressDiscreet"),String)
            End Get
            Set
                Me("ReturnAddressDiscreet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("skytribe@spottysworld.com")>  _
        Public Property DevelopmentModeEmailRecipient() As String
            Get
                Return CType(Me("DevelopmentModeEmailRecipient"),String)
            End Get
            Set
                Me("DevelopmentModeEmailRecipient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DevelopmentMode() As Boolean
            Get
                Return CType(Me("DevelopmentMode"),Boolean)
            End Get
            Set
                Me("DevelopmentMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Printer")>  _
        Public Property DevelopmentPrinterOrFile() As String
            Get
                Return CType(Me("DevelopmentPrinterOrFile"),String)
            End Get
            Set
                Me("DevelopmentPrinterOrFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultPrinterToUse() As String
            Get
                Return CType(Me("DefaultPrinterToUse"),String)
            End Get
            Set
                Me("DefaultPrinterToUse") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultPrinterTray() As String
            Get
                Return CType(Me("DefaultPrinterTray"),String)
            End Get
            Set
                Me("DefaultPrinterTray") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("637")>  _
        Public Property FreeAltitudeID() As Integer
            Get
                Return CType(Me("FreeAltitudeID"),Integer)
            End Get
            Set
                Me("FreeAltitudeID") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GiftCertificates.My.MySettings
            Get
                Return Global.GiftCertificates.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
